packages:
  - packages/*

minimumReleaseAge: 4320

# 2025/10/28 に `pnpm audit --fix` を実行した結果
overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  cross-spawn@<6.0.6: '>=6.0.6'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  nanoid@<3.3.8: '>=3.3.8'
  postcss@<8.4.31: '>=8.4.31'
  semver@<5.7.2: '>=5.7.2'
