name: Lint zenn-editor

on:
  pull_request:
    branches:
      - main
      - canary
    types: [opened, synchronize]

env:
  NPM_CONFIG_REGISTRY: https://npm.flatt.tech

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          version: 10.24.0

      - name: パッケージをインストール
        run: pnpm install

      - name: Lint
        run: pnpm lint-strict
