name: Lint zenn-editor

on:
  pull_request:
    branches:
      - main
      - canary
    types: [opened, synchronize]

env:
  NPM_CONFIG_REGISTRY: https://npm.flatt.tech

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10.24.0

      - name: パッケージをインストール
        run: pnpm install

      - name: Lint
        run: pnpm lint-strict
