name: Test zenn-editor

on:
  pull_request:
    branches:
      - main
      - canary
    types: [opened, synchronize]

env:
  NPM_CONFIG_REGISTRY: https://npm.flatt.tech

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10.24.0

      - name: パッケージをインストール
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run tests for zenn-markdown-html
        run: pnpm test
        working-directory: packages/zenn-markdown-html

      - name: Run tests for zenn-cli
        run: pnpm test
        working-directory: packages/zenn-cli

      - name: Run tests for zenn-embed-elements
        run: pnpm test
        working-directory: packages/zenn-embed-elements
